let world = {
    name: "Pakistan",
    provinces: [
        "sindh",
        "Punjab",
        "balochistan",
        "Kheber Pakhtoonkhaw"
    ],
    capital: "Islamabad",
    karachi: {
        "name": "city",
        "importance": "Largest",
        "knownAs": "City Of Light",
    },
    islamabad: {
        "name": "city",
        "importance": "beauty",
        "knownAs": "Beauty Of Country",
    },
    lahore: {
        "name": "City",
        "importance": "Small City"
    },
    PakistanCitiesDatabase: {
        karachi: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Sindh",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        lahore: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        faisalabad: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        serai: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "KPK",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        rawalpindi: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        multan: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        gujranwala: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        hyderabadCity: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Sindh",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        peshawar: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "KPK",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        abbottabad: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "KPK",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        islamabad: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Islamabad",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        quetta: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Balochistan",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        bannu: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "KPK",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        bahwalpur: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        sargodha: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        sialkotCity: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        sukkur: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Sindh",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        larkana: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Sindh",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        sheikhupura: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        mirpuskhas: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Sindh",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        rahimyarKhan: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        kohat: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "KPK",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        jahngSadr: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        gujrat: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        bardar: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "KPK",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        kasur: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        deraGhaziKhan: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        mastwala: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        nawabshah: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Sindh",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        okara: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Punjab",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        gilgit: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: "Gigit Baldistan",
            capital: "Admin",
            population: 1213000,
            polationProper: 11624219,
        },
        chiniot: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        sadiqabad: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        turbat: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        deraIsmailKhan: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chaman: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        zhob: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        mehra: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        parachinar: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        gawadar: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        kundian: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        shahdadKot: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        haripur: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        matiari: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        deraAllahyar: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        lodgran: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        batgram: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        thatta: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        bagh: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        badin: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        mansehra: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        ziarat: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        muzaffragharh: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        tando: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        deraMurad: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        karak: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        mardaan: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        uthal: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        nankhana: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        barkhan: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        barkhan: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        hafizabad: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        kotli: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        loralai: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        deraBugti: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        jhangCity: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        sahiwal: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        sanghar: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        pakPattan: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chakwal: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        khushab: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        ghotki: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        kohlu: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },

        khuzdar: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        awaran: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        nowshera: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        charsadda: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        qila: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        bahwalnagar: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        dadu: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        aliabad: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        lakki: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chillas: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        pishin: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        tank: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chiral: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        attock: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chiral: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chiral: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chiral: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chiral: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        chiral: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        nwshera: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        },
        dasu: {
            name: "city",
            latitude: 249056,
            ing: 67.082,
            country: "Pakistan",
            iso2: "PK",
            admin: " punjab",
            capital: "Admin",
            population: 1213000,
            populationProper: 11624219,
        }
    }
}